version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     networks:
       - backend
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ThisIsSecret
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ThisIsAlsoSecret

   wordpress:
     depends_on:
       - db
     image: wordpress:latest   
     volumes:
       - web_data:/var/www/html
     networks:
       - backend
       - frontend
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_PASSWORD: ThisIsAlsoSecret

networks:
  backend:
  frontend:

volumes:
  db_data: {}
  web_data: {}