version: '3.3'

services:
   db:
     image: mysql:5.7
     secrets:
      - db_root_password
      - db_dba_password
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_dba_password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     secrets:      
      - db_dba_password
     volumes:
       - web_data:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_dba_password

secrets:
  db_root_password:
    external: true
  db_dba_password:
    external: true

volumes:
  db_data: {}
  web_data: {}